name = "irtaqi-moodle-sync"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Cron trigger - يعمل كل ساعة
[triggers]
crons = ["*/30 * * * *"]

# Environment variables
[vars]
MOODLE_URL = "https://moodle.univ-tiaret.dz"
SUPABASE_URL = "https://bdjhurufqkalicjmokbk.supabase.co"
